#!/usr/bin/env python3
"""Generate MSC Irina-scale datacenter test data for Kuberina stress test.

Target: 150 nodes, 3000 pods, ~92% fill rate, hostile constraint matrix.
This script is a one-shot generator — run it once, commit the YAML.

Node types:
  - 100 Standard:        64C / 256G / 0GPU
  - 30 Memory-Optimized: 32C / 512G / 0GPU (label: disk=nvme)
  - 20 GPU-Optimized:    48C / 192G / 8GPU (label: gpu=nvidia-a100)

Workload design:
  - 50 microservices, each with 10-100 replicas = ~3000 pods total
  - 10 services with hard anti-affinity (no 2 pods on same node)
  - 5 affinity chains (A→B→C)
  - 500 GPU pods competing for 20 GPU nodes
  - Total resource ~92% of cluster capacity
"""

from __future__ import annotations

import math
import random
import yaml


SEED = 42
RNG = random.Random(SEED)

# ─── Zone distribution ───────────────────────────────────────────────
ZONES = ["us-east-1a", "us-east-1b", "us-east-1c"]


def _infra_header(infra: dict) -> str:
    """Describe the topology being written, counted from the data itself.

    WHY: the header was hardcoded as "100 Standard + 30 Memory + 20 GPU" and
    silently went stale when the node counts grew, leaving the file claiming a
    topology it did not contain (backlog B-3). Counting removes the failure mode.

    Example:
        >>> _infra_header({"nodes": [{"labels": {"tier": "gpu"}}]})
        '# MSC Irina Scale — 1-node datacenter topology\\n...'
    """
    tiers: dict[str, int] = {}
    for node in infra["nodes"]:
        tier = node.get("labels", {}).get("tier", "untiered")
        tiers[tier] = tiers.get(tier, 0) + 1
    # Largest tier first — the reader wants the shape of the cluster, not an alphabet.
    mix = " + ".join(f"{count} {tier}"
                     for tier, count in sorted(tiers.items(), key=lambda kv: -kv[1]))
    return (
        f"# MSC Irina Scale — {len(infra['nodes'])}-node datacenter topology\n"
        "# Generated by gen_irina_testdata.py\n"
        f"# {mix} nodes\n\n"
    )


def _workloads_header(workloads: dict) -> str:
    """Describe the workload being written, counted from the data itself."""
    services = sum(len(specs) for specs in workloads.get("namespaces", {}).values())
    return (
        f"# MSC Irina Scale — {len(workloads['pods'])}-pod workload manifest\n"
        "# Generated by gen_irina_testdata.py\n"
        f"# {services} microservices with hostile constraint matrix\n\n"
    )


def generate_infra() -> dict:
    """Build the datacenter topology across three node types."""
    nodes = []
    daemonsets = _build_daemonsets()

    # 400 Standard nodes: 64C / 256G
    for i in range(400):
        nodes.append(_make_node(
            name=f"std-{i:03d}",
            cpu=64.0, ram=256.0, gpu=0.0,
            storage=1000.0, disk_read=500.0, disk_write=200.0,
            net_in=1000.0, net_out=1000.0,
            labels={"tier": "standard", "disk": "ssd"},
            zone=ZONES[i % 3], rack=f"rack-{i % 5}",
        ))

    # 120 Memory-Optimized nodes: 32C / 512G
    for i in range(120):
        nodes.append(_make_node(
            name=f"mem-{i:03d}",
            cpu=32.0, ram=512.0, gpu=0.0,
            storage=2000.0, disk_read=2000.0, disk_write=1500.0,
            net_in=2000.0, net_out=2000.0,
            labels={"tier": "memory", "disk": "nvme"},
            zone=ZONES[i % 3], rack=f"rack-{i % 5}",
        ))

    # 100 GPU nodes: 48C / 192G / 8GPU
    for i in range(100):
        nodes.append(_make_node(
            name=f"gpu-{i:03d}",
            cpu=48.0, ram=192.0, gpu=8.0,
            storage=500.0, disk_read=1000.0, disk_write=1000.0,
            net_in=10000.0, net_out=10000.0,
            labels={"tier": "gpu", "gpu": "nvidia-a100", "disk": "nvme"},
            zone=ZONES[i % 3], rack=f"rack-{i % 2}",
        ))

    return {"nodes": nodes, "daemonsets": daemonsets}


def _resources(
    cpu: float, ram: float, gpu: float, storage: float,
    disk_read: float, disk_write: float, net_in: float, net_out: float,
) -> dict:
    """Emit one 8-dimensional resource block in Kuberina IR v0.2.0 shape.

    WHY: the I/O dimensions nest under `disk` and `network`. Emitting them flat
    as `disk_read`/`net_in` parses without error — serde ignores unknown fields —
    but silently yields zero I/O demand and unconstrained I/O capacity, so the
    solver plans in four dimensions while believing it plans in eight.

    Example:
        >>> _resources(64.0, 256.0, 0.0, 1000.0, 500.0, 200.0, 1000.0, 1000.0)["disk"]
        {'read': 500.0, 'write': 200.0}
    """
    return {
        "cpu": cpu,
        "ram": ram,
        "gpu": gpu,
        "storage": storage,
        "disk": {"read": disk_read, "write": disk_write},
        "network": {"in": net_in, "out": net_out},
    }


def _make_node(
    name: str,
    cpu: float, ram: float, gpu: float,
    storage: float, disk_read: float, disk_write: float,
    net_in: float, net_out: float,
    labels: dict[str, str],
    zone: str, rack: str,
) -> dict:
    """Create a single node entry."""
    return {
        "name": name,
        "allocatable": _resources(
            cpu, ram, gpu, storage, disk_read, disk_write, net_in, net_out,
        ),
        "labels": {**labels, "node-role": "worker"},
        "taints": [],
        "zone": zone,
        "rack": rack,
    }


def _build_daemonsets() -> list[dict]:
    """System DaemonSets consuming ~3-5% overhead per node."""
    return [
        {"name": "kube-proxy",
         "resources": _resources(0.5, 0.5, 0.0, 1.0, 1.0, 1.0, 10.0, 10.0),
         "nodeSelector": {}, "tolerations": []},
        {"name": "calico-node",
         "resources": _resources(1.0, 1.0, 0.0, 2.0, 5.0, 5.0, 50.0, 50.0),
         "nodeSelector": {}, "tolerations": []},
        {"name": "node-exporter",
         "resources": _resources(0.25, 0.25, 0.0, 0.5, 10.0, 2.0, 5.0, 15.0),
         "nodeSelector": {}, "tolerations": []},
        {"name": "fluentd",
         "resources": _resources(0.5, 1.0, 0.0, 5.0, 5.0, 20.0, 5.0, 30.0),
         "nodeSelector": {}, "tolerations": []},
    ]


# ─── Workload generation ─────────────────────────────────────────────

# WHY these exact numbers: we need total resource ~92% of cluster capacity
# after DaemonSet deduction.
#
# Cluster raw capacity:
#   Standard:  100 * 64C  = 6400C,  100 * 256G  = 25600G
#   Memory:     30 * 32C  =  960C,   30 * 512G  = 15360G
#   GPU:        20 * 48C  =  960C,   20 * 192G  =  3840G
#   Total:                  8320C                  44800G,  160 GPU
#
# DaemonSet overhead per node: 2.25C, 2.75G
#   Total overhead: 150 * 2.25 = 337.5C,  150 * 2.75 = 412.5G
#
# Net capacity: 7982.5C, 44387.5G, 160 GPU
# Target 92%:   7344C,   40836G,   147 GPU

# Service definitions: (name, namespace, replicas, cpu, ram, gpu, storage, dr, dw, ni, no, node_selector, is_anti_affinity_spread, topology_key)
SERVICES: list[tuple] = [
    # ── Tier 1: GPU workloads (~300 pods, 152 GPU units on 20 nodes) ───
    ("llm-inference",     "ai",        40, 6.0,  24.0, 1.0, 20.0,  50.0,  10.0, 500.0, 500.0, {"gpu": "nvidia-a100"}, True, "zone"),
    ("embedding-server",  "ai",        24, 5.0,  16.0, 1.0, 10.0,  20.0,  10.0, 200.0, 200.0, {"gpu": "nvidia-a100"}, True, "rack"),
    ("training-worker",   "ai",        16,12.0,  48.0, 4.0, 100.0, 200.0, 200.0,1000.0,1000.0,{"gpu": "nvidia-a100"}, False, None),
    ("vision-pipeline",   "ai",        24, 4.0,  12.0, 1.0, 50.0, 100.0,  50.0, 300.0, 300.0, {"gpu": "nvidia-a100"}, True, "zone"),
    ("recommendation-ml", "ai",        80, 3.0,  10.0, 0.0, 10.0,  50.0,  10.0, 100.0, 100.0, {}, True, "zone"),
    ("feature-store",     "ai",       100, 2.0,   6.0, 0.0, 10.0,  20.0,  10.0, 150.0, 150.0, {}, False, None),

    # ── Tier 2: Core platform (heavy CPU, anti-affinity spread) ────────
    ("api-gateway",       "platform", 100, 6.0,  12.0, 0.0, 5.0,   10.0,  10.0, 800.0, 800.0, {},                     True, "zone"),
    ("payment-service",   "fintech",  100, 4.0,   8.0, 0.0, 5.0,   10.0,  10.0, 100.0, 100.0, {},                     True, "rack"),
    ("order-service",     "commerce",  80, 4.0,  10.0, 0.0, 10.0,  10.0,  20.0, 200.0, 200.0, {},                     True, "zone"),
    ("inventory-service", "commerce",  60, 3.0,   6.0, 0.0, 10.0,  30.0,  10.0, 150.0, 150.0, {},                     True, "rack"),

    # ── Tier 3: Data layer (memory-heavy, nvme required) ──────────────
    ("postgres-primary",  "database",  30, 6.0,  96.0, 0.0, 500.0, 800.0, 800.0, 500.0, 500.0, {"disk": "nvme"},       True, "zone"),
    ("postgres-replica",  "database",  60, 3.0,  48.0, 0.0, 500.0, 500.0, 800.0, 100.0, 500.0, {"disk": "nvme"},       False, None),
    ("redis-cache",       "cache",    100, 2.0,  24.0, 0.0, 5.0,   10.0,  10.0, 600.0, 600.0, {},                     True, "rack"),
    ("elasticsearch",     "search",    30, 6.0,  96.0, 0.0, 300.0, 600.0, 400.0, 300.0, 300.0, {"disk": "nvme"},       True, "zone"),
    ("kafka-broker",      "streaming", 30, 6.0,  48.0, 0.0, 200.0, 400.0, 800.0, 800.0, 800.0, {"disk": "nvme"},       False, None),

    # ── Tier 4: Web frontend + BFF ─────────────────────────────────────
    ("web-frontend",      "frontend", 100, 3.0,   6.0, 0.0, 5.0,   10.0,  5.0,  300.0, 500.0, {},                     True, "rack"),
    ("mobile-bff",        "frontend",  80, 2.0,   4.0, 0.0, 5.0,   10.0,  5.0,  200.0, 300.0, {},                     False, None),
    ("admin-dashboard",   "frontend",  30, 2.0,   4.0, 0.0, 5.0,   10.0,  5.0,   50.0,  50.0, {},                     False, None),

    # ── Tier 5: Background workers ─────────────────────────────────────
    ("email-worker",      "workers",   80, 2.0,   4.0, 0.0, 10.0,  20.0,  10.0,  50.0,  50.0, {},                     False, None),
    ("notification-svc",  "workers",   60, 2.0,   3.0, 0.0, 10.0,  10.0,  10.0, 100.0, 100.0, {},                     False, None),
    ("report-generator",  "workers",   80, 3.0,   6.0, 0.0, 20.0,  50.0, 100.0,  50.0,  50.0, {},                     False, None),
    ("image-processor",   "workers",   60, 4.0,   8.0, 0.0, 50.0, 100.0, 100.0, 200.0, 200.0, {},                     False, None),
    ("pdf-renderer",      "workers",   40, 3.0,   6.0, 0.0, 20.0,  50.0,  50.0, 100.0, 100.0, {},                     False, None),

    # ── Tier 6: Observability stack ────────────────────────────────────
    ("prometheus",        "monitoring", 30, 3.0,  12.0, 0.0, 200.0, 100.0, 400.0, 300.0,  50.0, {},                    False, None),
    ("grafana",           "monitoring", 20, 2.0,   4.0, 0.0, 10.0,  20.0,  10.0,  50.0, 100.0, {},                    False, None),
    ("jaeger-collector",  "monitoring", 30, 3.0,   6.0, 0.0, 100.0, 50.0,  200.0, 400.0,  50.0, {},                    False, None),
    ("loki",              "monitoring", 30, 3.0,  12.0, 0.0, 200.0, 100.0, 400.0, 300.0,  50.0, {},                    False, None),

    # ── Tier 7: Auth & Security ────────────────────────────────────────
    ("auth-service",      "security", 100, 3.0,   6.0, 0.0, 5.0,   10.0,  10.0,  50.0,  50.0, {},                     True, "zone"),
    ("vault",             "security",  20, 2.0,   4.0, 0.0, 20.0,  30.0,  50.0,  20.0,  20.0, {},                     True, "rack"),
    ("cert-manager",      "security",  20, 1.0,   2.0, 0.0, 5.0,   10.0,  10.0,  10.0,  10.0, {},                     False, None),

    # ── Tier 8: Internal tools ─────────────────────────────────────────
    ("cronjob-scheduler", "internal",  40, 1.5,   3.0, 0.0, 5.0,   10.0,  10.0,  10.0,  10.0, {},                     False, None),
    ("config-server",     "internal",  20, 1.0,   2.0, 0.0, 5.0,   10.0,  10.0,  20.0,  20.0, {},                     False, None),
    ("service-mesh-proxy","internal", 100, 1.0,   2.0, 0.0, 2.0,    5.0,   5.0, 200.0, 200.0, {},                     False, None),

    # ── Tier 9: Fillers (reach ~2700 pods, boost CPU fill to ~92%) ─────
    ("log-aggregator",    "logging",   80, 2.0,   6.0, 0.0, 50.0,  50.0, 100.0, 200.0,  50.0, {},                     False, None),
    ("metrics-relay",     "logging",   60, 1.0,   2.0, 0.0, 5.0,   10.0,  10.0, 100.0, 100.0, {},                     False, None),
    ("healthcheck-agent", "ops",      100, 1.0,   2.0, 0.0, 2.0,    5.0,   5.0,  10.0,  10.0, {},                     False, None),
    ("dns-resolver",      "ops",       40, 1.0,   2.0, 0.0, 2.0,    5.0,   5.0,  50.0,  50.0, {},                     False, None),
    ("rate-limiter",      "platform",  80, 2.0,   4.0, 0.0, 5.0,    5.0,   5.0, 100.0, 100.0, {},                     False, None),
    ("session-store",     "platform",  80, 1.0,   6.0, 0.0, 10.0,  10.0,  20.0, 150.0, 150.0, {},                     False, None),
    ("task-queue",        "workers",   60, 2.0,   4.0, 0.0, 10.0,  20.0,  20.0,  50.0,  50.0, {},                     False, None),
    ("webhook-relay",     "platform",  40, 1.0,   2.0, 0.0, 5.0,    5.0,   5.0, 100.0, 100.0, {},                     False, None),
    ("audit-logger",      "security",  40, 1.0,   2.0, 0.0, 20.0,  10.0,  50.0,  50.0,  10.0, {},                     False, None),
    ("geo-service",       "platform",  40, 2.0,   4.0, 0.0, 10.0,  50.0,  10.0, 100.0, 100.0, {},                     False, None),
    ("search-indexer",    "search",    40, 3.0,  12.0, 0.0, 100.0, 200.0, 100.0, 150.0, 150.0, {"disk": "nvme"},       False, None),
    ("cdn-origin",        "frontend",  60, 2.0,   4.0, 0.0, 50.0, 200.0,  10.0,  50.0, 400.0, {},                     False, None),
    ("ab-test-engine",    "platform",  20, 1.0,   2.0, 0.0, 5.0,   10.0,  10.0,  20.0,  20.0, {},                     False, None),
    ("feature-flags",     "platform",  20, 1.0,   2.0, 0.0, 2.0,    5.0,   5.0,  10.0,  10.0, {},                     False, None),
    ("user-profile-svc",  "platform",  80, 2.0,   4.0, 0.0, 10.0,  20.0,  20.0,  50.0,  50.0, {},                     False, None),
    ("chat-service",      "comms",     60, 2.0,   4.0, 0.0, 10.0,  10.0,  20.0, 100.0, 100.0, {},                     False, None),
]

# WHY: 5 affinity chains create cascading dependencies that force the GA
# to co-locate entire stacks — exponentially harder than pairwise affinity.
AFFINITY_CHAINS: list[list[str]] = [
    ["web-frontend", "api-gateway", "redis-cache"],
    ["order-service", "payment-service", "postgres-primary"],
    ["mobile-bff", "auth-service", "vault"],
    ["llm-inference", "embedding-server", "feature-store"],
    ["prometheus", "grafana", "loki"],
]

# WHY: anti-affinity pairs across tiers create cross-cutting constraints
# that prevent the GA from simply partitioning by tier.
ANTI_AFFINITY_CROSS: list[tuple[str, str]] = [
    ("postgres-primary", "elasticsearch"),  # both heavy — separate them
    ("kafka-broker", "postgres-primary"),   # I/O isolation
    ("training-worker", "llm-inference"),   # GPU bandwidth contention
    ("api-gateway", "image-processor"),     # CPU contention
    ("redis-cache", "kafka-broker"),        # memory contention
]


def generate_workloads() -> dict:
    """Build 3000-pod workload manifest with hostile constraint matrix."""
    namespaces: dict[str, list[dict]] = {}
    pods: list[dict] = []
    pod_name_registry: dict[str, list[str]] = {}

    for svc_def in SERVICES:
        svc_name, ns_name, replicas = svc_def[0], svc_def[1], svc_def[2]
        
        svc_entry = {
            "name": svc_name,
            "replicas": replicas,
            "requests": _resources(
                svc_def[3], svc_def[4], svc_def[5], svc_def[6],
                svc_def[7], svc_def[8], svc_def[9], svc_def[10],
            )
        }
        
        if svc_def[11]: svc_entry["nodeSelector"] = svc_def[11]
        if svc_def[13]: svc_entry["topologySpread"] = {"maxSkew": 1, "topologyKey": svc_def[13]}
        
        namespaces.setdefault(ns_name, []).append(svc_entry)
        
        # Build registry for constraints
        names = [f"{svc_name}-{r:04d}" for r in range(replicas)]
        pod_name_registry[svc_name] = names
        
        # Flatten for legacy constraint logic
        for name in names:
            p = svc_entry.copy()
            p["name"] = name
            p["namespace"] = ns_name
            pods.append(p)

    _apply_anti_affinity_spread(pods, pod_name_registry)
    _apply_affinity_chains(pods, pod_name_registry)
    _apply_cross_anti_affinity(pods, pod_name_registry)

    return {"namespaces": namespaces, "pods": pods}


def _apply_anti_affinity_spread(
    pods: list[dict],
    registry: dict[str, list[str]],
) -> None:
    """For spread services, each pod anti-affines with all siblings.

    WHY: this forces the GA to spread pods across nodes — the most
    expensive constraint type because it creates O(n^2) pairwise checks.
    We limit to first 5 siblings to avoid YAML bloat while keeping
    the constraint pressure high.
    """
    spread_services = [s[0] for s in SERVICES if s[7]]

    for svc_name in spread_services:
        svc_pods = registry[svc_name]
        for pod in pods:
            if not pod["name"].startswith(svc_name + "-"):
                continue

            # WHY: pick up to 5 random siblings to anti-affine with.
            # Full O(n^2) would create 10000-entry lists for 100 replicas.
            siblings = [n for n in svc_pods if n != pod["name"]]
            targets = RNG.sample(siblings, min(5, len(siblings)))
            pod.setdefault("antiAffinity", []).extend(targets)


def _apply_affinity_chains(
    pods: list[dict],
    registry: dict[str, list[str]],
) -> None:
    """Link services in affinity chains: A[i] → B[i] → C[i].

    WHY: creates cascading co-location pressure. If A must be with B
    and B must be with C, then A-B-C must all land on the same node.
    This is transitively explosive for the constraint solver.
    """
    for chain in AFFINITY_CHAINS:
        min_replicas = min(len(registry[svc]) for svc in chain)
        link_count = min(min_replicas, 30)  # cap at 30 links per chain

        for i in range(link_count):
            for j in range(len(chain) - 1):
                src_svc = chain[j]
                dst_svc = chain[j + 1]
                src_pod_name = registry[src_svc][i]
                dst_pod_name = registry[dst_svc][i]

                # Find the actual pod dict and add affinity
                for pod in pods:
                    if pod["name"] == src_pod_name:
                        pod.setdefault("affinity", []).append(dst_pod_name)
                    elif pod["name"] == dst_pod_name:
                        pod.setdefault("affinity", []).append(src_pod_name)


def _apply_cross_anti_affinity(
    pods: list[dict],
    registry: dict[str, list[str]],
) -> None:
    """Cross-tier anti-affinity: pods from different services repel each other.

    WHY: prevents the GA from simply partitioning workloads by tier.
    A postgres-primary pod must not share a node with an elasticsearch pod.
    """
    for svc_a, svc_b in ANTI_AFFINITY_CROSS:
        pods_a = registry[svc_a]
        pods_b = registry[svc_b]
        link_count = min(len(pods_a), len(pods_b), 20)

        for i in range(link_count):
            for pod in pods:
                if pod["name"] == pods_a[i]:
                    pod.setdefault("antiAffinity", []).append(pods_b[i])
                elif pod["name"] == pods_b[i]:
                    pod.setdefault("antiAffinity", []).append(pods_a[i])


def compute_resource_summary(infra: dict, workloads: dict) -> None:
    """Print resource utilization analysis for verification."""
    # Node capacity
    total_cpu = sum(n["allocatable"]["cpu"] for n in infra["nodes"])
    total_ram = sum(n["allocatable"]["ram"] for n in infra["nodes"])
    total_gpu = sum(n["allocatable"]["gpu"] for n in infra["nodes"])

    # DaemonSet overhead
    ds_cpu = sum(d["resources"]["cpu"] for d in infra["daemonsets"])
    ds_ram = sum(d["resources"]["ram"] for d in infra["daemonsets"])
    overhead_cpu = ds_cpu * len(infra["nodes"])
    overhead_ram = ds_ram * len(infra["nodes"])

    net_cpu = total_cpu - overhead_cpu
    net_ram = total_ram - overhead_ram

    # Pod requests
    pod_cpu = sum(p["requests"]["cpu"] for ns in workloads.get("namespaces", {}).values() for p in ns for _ in range(p["replicas"]))
    pod_ram = sum(p["requests"]["ram"] for ns in workloads.get("namespaces", {}).values() for p in ns for _ in range(p["replicas"]))
    pod_gpu = sum(p["requests"]["gpu"] for ns in workloads.get("namespaces", {}).values() for p in ns for _ in range(p["replicas"]))

    fill_cpu = pod_cpu / net_cpu * 100
    fill_ram = pod_ram / net_ram * 100
    fill_gpu = pod_gpu / total_gpu * 100 if total_gpu > 0 else 0

    total_pods = sum(p.get("replicas", 1) for ns in workloads.get("namespaces", {}).values() for p in ns)
    total_nodes = len(infra["nodes"])

    anti_aff_count = sum(
        len(p.get("antiAffinity", [])) for p in workloads["pods"]
    )
    aff_count = sum(
        len(p.get("affinity", [])) for p in workloads["pods"]
    )

    print(f"{'═' * 60}")
    print(f"  MSC IRINA SCALE — Resource Summary")
    print(f"{'═' * 60}")
    print(f"  Nodes:          {total_nodes}")
    print(f"  Pods:           {total_pods}")
    print(f"  Constraints:    {anti_aff_count} anti-affinity + {aff_count} affinity")
    print(f"{'─' * 60}")
    print(f"  Cluster CPU:    {total_cpu:.0f} cores (net: {net_cpu:.1f})")
    print(f"  Cluster RAM:    {total_ram:.0f} GiB  (net: {net_ram:.1f})")
    print(f"  Cluster GPU:    {total_gpu:.0f} units")
    print(f"{'─' * 60}")
    print(f"  Pod CPU demand: {pod_cpu:.0f} cores  ({fill_cpu:.1f}% fill)")
    print(f"  Pod RAM demand: {pod_ram:.0f} GiB   ({fill_ram:.1f}% fill)")
    print(f"  Pod GPU demand: {pod_gpu:.0f} units  ({fill_gpu:.1f}% fill)")
    print(f"{'═' * 60}\n")


def main() -> None:
    """Generate and write the MSC Irina test data files."""
    infra = generate_infra()
    workloads = generate_workloads()

    compute_resource_summary(infra, workloads)

    infra_path = "testdata/irina_infra.yaml"
    workloads_path = "testdata/irina_workloads.yaml"

    with open(infra_path, "w") as f:
        f.write(_infra_header(infra))
        yaml.dump(infra, f, default_flow_style=False, sort_keys=False,
                  allow_unicode=True, width=120)

    with open(workloads_path, "w") as f:
        f.write(_workloads_header(workloads))
        yaml.dump(workloads, f, default_flow_style=False, sort_keys=False,
                  allow_unicode=True, width=120)

    print(f"  Written: {infra_path}")
    print(f"  Written: {workloads_path}")


if __name__ == "__main__":
    main()
